In [16]:
# Tractem de veure com es poden desar i carregar els fitxers amb els mallats.

In [17]:
import numpy as np
elem = np.array([[1, 2, 3],[3, 4, 5]])
nodes = np.random.rand(5,2)
print(nodes)
print(elem)

[[0.85739611 0.64721737]
 [0.87525397 0.63954851]
 [0.85601029 0.46410605]
 [0.27629252 0.33257156]
 [0.89765521 0.1944686 ]]
[[1 2 3]
 [3 4 5]]


In [18]:
np.savez("random_mesh.npz", nodes = nodes, elem = elem)

In [19]:

loaded_data = np.load("random_mesh.npz")
nodes_1 = loaded_data['nodes']
elem_1 = loaded_data['elem']

print(nodes_1)
print(type(nodes))
print(elem_1)
print(type(elem_1))

[[0.85739611 0.64721737]
 [0.87525397 0.63954851]
 [0.85601029 0.46410605]
 [0.27629252 0.33257156]
 [0.89765521 0.1944686 ]]
<class 'numpy.ndarray'>
[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
